apiVersion: v1
kind: Secret
metadata:
  name: mail-worker-secret
  namespace: mail-worker
type: Opaque
data:
  # REDIS
  REDIS_PASSWORD: U3VwZXJTZW5oYVNlZ3VyYTEyMyE=
  # Provider de email
  GMAIL_USER: dGVzdGVAdGVzdGUuY29t
  GMAIL_PASSWORD: Z21rYyB4cG5iIHBqZGIgZmlvbQ==
  GMAIL_SECURE: ZmFsc2U=