# bash
# echo -n 'admin' | base64          # Saída: YWRtaW4=
# echo -n 'admin123' | base64       # Saída: YWRtaW4xMjM=
# echo -n 'ecommerce_db' | base64   # Saída: ZWNvbW1lcmNlX2Ri

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: namespace-name
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=          # Valor base64 de 'admin'
  POSTGRES_PASSWORD: YWRtaW4xMjM= # Valor base64 de 'admin123'
  POSTGRES_DB: ZWNvbW1lcmNlX2Ri   # Valor base64 de 'ecommerce_db'